[package]
org = "ballerina"
name = "grpc_tests"
version = "1.7.3"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "grpc-native"
version = "1.7.3-SNAPSHOT"
path = "../native/build/libs/grpc-native-1.7.3-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/grpc-test-utils-1.7.3-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ballerina-cli-2201.5.0.jar"
scope = "testOnly"

[[platform.java11.dependency]]
groupId = "com.google.protobuf"
artifactId = "protobuf-java"
version = "3.20.3"
path = "./lib/protobuf-java-3.20.3.jar"

[[platform.java11.dependency]]
groupId = "com.google.api.grpc"
artifactId = "proto-google-common-protos"
version = "1.17.0"
path = "./lib/proto-google-common-protos-1.17.0.jar"

[[platform.java11.dependency]]
groupId = "org.ballerinalang"
artifactId = "formatter-core"
version = "2201.5.0"
path = "./lib/formatter-core-2201.5.0.jar"
